[package]

name = "html5ever"
version = "0.0.0"
authors = [ "The html5ever Project Developers" ]

[lib]
name = "html5ever"

# https://github.com/rust-lang/cargo/issues/1512
doctest = false

[dependencies]
time = "0"
log = "0"
phf = "0.7"
phf_macros = "0.7"

[dependencies.string_cache]
git = "https://github.com/kumabook/string-cache"
[dependencies.string_cache_plugin]
git = "https://github.com/kumabook/string-cache"

[dependencies.mac]
git = "https://github.com/reem/rust-mac"

[dependencies.html5ever_macros]
path = "macros"

[dev-dependencies]
rustc-serialize = "0"

[dev-dependencies.test_util]
path = "test_util"

[profile.dev]
debug = false

[profile.test]
debug = false
